package com.bank.transactions.controller;
import com.bank.transactions.model.exceptions.NotFoundException;
import com.bank.transactions.service.TransactionService;
import com.bank.transactions.model.business.Transaction;

import java.io.IOException;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.api.core.ApiFuture;
import com.google.cloud.pubsub.v1.AckReplyConsumer;
import com.google.cloud.pubsub.v1.MessageReceiver;
import com.google.cloud.pubsub.v1.Publisher;
import com.google.cloud.pubsub.v1.Subscriber;
import com.google.protobuf.ByteString;
import com.google.pubsub.v1.ProjectSubscriptionName;
import com.google.pubsub.v1.PubsubMessage;
import com.google.pubsub.v1.TopicName;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.view.RedirectView;

@RestController
@RequestMapping("/transactions")
@Slf4j
public class TransactionController {

  private final TransactionService trxsService;

  public TransactionController(TransactionService trxsService) {
    this.trxsService = trxsService;
  }
  @CrossOrigin(origins = "${CORS_ORIGIN_URL}") // Permitimos solicitudes desde http://localhost:3000
  @PostMapping //Insert Data Firestore
  @ResponseStatus(HttpStatus.CREATED)
  public Transaction create(@RequestBody Transaction trx) {
    return trxsService.add(trx);
  }

  @GetMapping("/{id}") //Get data per ID
  public Transaction read(@PathVariable String id) {
    return Optional.ofNullable(trxsService.get(id)).orElseThrow(NotFoundException::new);
  }
  @GetMapping("/all") //Get all data
  public List<Transaction> getAllTransactions() {
    return trxsService.getAllTransactions();
  }
  @CrossOrigin(origins = "${CORS_ORIGIN_URL}") // Permitimos solicitudes desde http://localhost:3000
  @GetMapping("/online-payments")
  public List<Transaction> getAllMongoDBTransactions() {
    return trxsService.getAllMongoDBTransactions();
  }
  //Pubsub Controller
  @Value("${pubsub.project-id}")
  private String projectId;

  @Value("${pubsub.topic-id}")
  private String topicId;

  @Value("${pubsub.subscription-id}")
  private String subscriptionId;

  @CrossOrigin(origins = "${CORS_ORIGIN_URL}") // Permitimos solicitudes desde http://localhost:3000
  @RequestMapping("/publish-transaction") //Insert data Transaction Topic Pubsub
  public ResponseEntity<String> publishMessage(@RequestBody String sampleJsonMessage)
          throws InterruptedException, IOException, ExecutionException {

    TopicName topicName = TopicName.of(projectId, topicId);

    Publisher publisher = null;

    try {
      publisher = Publisher.newBuilder(topicName).build();
      ByteString data = ByteString.copyFromUtf8(sampleJsonMessage);

      PubsubMessage pubSubMessage = PubsubMessage.newBuilder().setData(data).build();

      ApiFuture<String> messageIdFuture = publisher.publish(pubSubMessage);

      //log.info("Message Id generated by pubsub {}", messageIdFuture.get());

      return new ResponseEntity<>("Message Id generated by Topic :" + messageIdFuture.get(), HttpStatus.OK);

    } finally {
      if (publisher != null) {
        publisher.shutdown();
        publisher.awaitTermination(1, TimeUnit.MINUTES);
      }
    }
  }

  @RequestMapping("/subscribe") //pull data Transaction Subscription Topic Pubsub
  public ResponseEntity<String> receiveMessage() {

    ProjectSubscriptionName subscriptionName = ProjectSubscriptionName.of(projectId, subscriptionId);

    var wrapper = new Object() { String messageFromPubSub; };

    MessageReceiver receiver = (PubsubMessage message, AckReplyConsumer consumer) -> {

      //log.info("Message Id : " + message.getMessageId());
      wrapper.messageFromPubSub = message.getData().toStringUtf8();
      //log.info("Message : {}", wrapper.messageFromPubSub);
      consumer.ack();
    };

    Subscriber subscriber = null;
    try {
      subscriber = Subscriber.newBuilder(subscriptionName, receiver).build();
      subscriber.startAsync().awaitRunning();
      subscriber.awaitTerminated(2, TimeUnit.SECONDS);
    } catch (TimeoutException e) {
      subscriber.stopAsync();
    }

    return new ResponseEntity<>(wrapper.messageFromPubSub, HttpStatus.OK);
  }
}
