# server properties
server:
  servlet:
    context-path: /bank

# spring properties
spring:
  cloud:
    gcp:
      project-id: transactions-project
      pubsub:
        emulator-host: localhost:8085
      firestore:
        emulator:
          enabled: false #if true --activate emulator
        host-port: ${host.port.firestore} #localhost:9080
        project-id: ${project.id.gcloud} #transactions-project
  data:
    mongodb:
      uri: ${spring.data.mongodb.uri}
      host: localhost
      port: 27017
      database: bank
      collection: transactions
# custom properties
config:
  pubsub:
    test-subscription: test-sub
  storage:
    emulator-host: localhost:9199 # gcp starter does not have this property
    default-bucket: transactions-emulator.chmoro.com
