# server properties
server:
  servlet:
    context-path: /bank

# spring && mongodb properties
spring:
  cloud:
    gcp:
      project-id: transactions-project
      firestore:
        emulator:
          enabled: ${MODE_EMULATOR} #if true --activate emulator ${mode.emulator}
        host-port: ${host.port.firestore} #localhost:9080
        project-id: ${project.id.gcloud} #transactions-project
  data:
    mongodb:
      uri: ${spring.data.mongodb.uri}
      host: localhost
      port: 27017
      database: bank
      collection: transactions