# server properties
server:
  servlet:
    context-path: /bank
  port: 8090
# spring && mongodb properties
spring:
  cloud:
    gcp:
      project-id: detector-transactions-project
      firestore:
        emulator:
          enabled: ${MODE_EMULATOR} #if true --activate emulator ${mode.emulator}
        host-port: ${host.port.firestore} #localhost:9080
        project-id: ${project.id.gcloud} #detector-transactions-project
        credentials:
          location: ${credentials.user} # # Path to your service account key file from environment variable file:///C:/
  data:
    mongodb:
      uri: ${spring.data.mongodb.uri}
      host: localhost
      port: 27017
      database: bank
      collection: transactions

# Pub/Sub properties
pubsub:
  topic-id: ${pubsub.topic-id} #online-payments
  project-id: ${pubsub.project-id} #detector-transactions-project
  subscription-id: ${pubsub.subscription-id} #online-payments-sub